// <auto-generated />
using System;
using System.Collections.Generic;
using Cogni.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cogni.Migrations
{
    [DbContext(typeof(CogniDbContext))]
    [Migration("20261007074131_TagCategoryBookmarks")]
    partial class TagCategoryBookmarks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cogni.Database.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_article");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Annotation")
                        .HasColumnType("text");

                    b.Property<string>("ArticleBody")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("article_body");

                    b.Property<string>("ArticleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("article_name");

                    b.Property<string>("ArticlePreview")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int?>("ReadsNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("article_pkey");

                    b.HasIndex("IdUser");

                    b.ToTable("article", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.ArticleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.HasKey("Id")
                        .HasName("article_images_pkey");

                    b.HasIndex("ArticleId");

                    b.ToTable("article_images", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.Avatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_added")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("avatars_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("avatars", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<bool>("isDm")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dm");

                    b.HasKey("Id");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.ChatMember", b =>
                {
                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ChatId", "UserId");

                    b.ToTable("chat_members", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.Friend", b =>
                {
                    b.Property<int>("FriendId")
                        .HasColumnType("integer")
                        .HasColumnName("friend_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_added")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FriendId", "UserId")
                        .HasName("friends_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("friends", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.Like", b =>
                {
                    b.Property<DateTime?>("LikedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("liked_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.MbtiQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_mbti_question");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Question")
                        .HasMaxLength(130)
                        .HasColumnType("character varying(130)")
                        .HasColumnName("question");

                    b.HasKey("Id")
                        .HasName("mbti_question_pkey");

                    b.ToTable("mbti_question", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.MbtiType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_mbti_type");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameOfType")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("name_of_type");

                    b.HasKey("Id")
                        .HasName("mbti_type_pkey");

                    b.ToTable("mbti_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameOfType = "ENFJ"
                        },
                        new
                        {
                            Id = 2,
                            NameOfType = "ENTJ"
                        },
                        new
                        {
                            Id = 3,
                            NameOfType = "ENFP"
                        },
                        new
                        {
                            Id = 4,
                            NameOfType = "ENTP"
                        },
                        new
                        {
                            Id = 5,
                            NameOfType = "INFJ"
                        },
                        new
                        {
                            Id = 6,
                            NameOfType = "INTJ"
                        },
                        new
                        {
                            Id = 7,
                            NameOfType = "INFP"
                        },
                        new
                        {
                            Id = 8,
                            NameOfType = "INTP"
                        },
                        new
                        {
                            Id = 9,
                            NameOfType = "ISFP"
                        },
                        new
                        {
                            Id = 10,
                            NameOfType = "ISFJ"
                        },
                        new
                        {
                            Id = 11,
                            NameOfType = "ESFP"
                        },
                        new
                        {
                            Id = 12,
                            NameOfType = "ESFJ"
                        },
                        new
                        {
                            Id = 13,
                            NameOfType = "ISTJ"
                        },
                        new
                        {
                            Id = 14,
                            NameOfType = "ISTP"
                        },
                        new
                        {
                            Id = 15,
                            NameOfType = "ESTP"
                        },
                        new
                        {
                            Id = 16,
                            NameOfType = "ESTJ"
                        });
                });

            modelBuilder.Entity("Cogni.Database.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("MessageId"));

                    b.Property<List<string>>("Attachments")
                        .HasColumnType("text[]");

                    b.Property<int?>("AvatarId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<bool>("IsFunctional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_functional");

                    b.Property<string>("Msg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("msg");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.HasKey("MessageId");

                    b.HasIndex("AvatarId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.MessageStatus", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<int>("LastReaden")
                        .HasColumnType("integer")
                        .HasColumnName("last_readen");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ChatId");

                    b.HasIndex("ChatId");

                    b.HasIndex("MessageId");

                    b.ToTable("message_statuses", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_post");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<string>("PostBody")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("post_body");

                    b.HasKey("Id")
                        .HasName("post_pkey");

                    b.HasIndex("IdUser");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.PostImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("post_images_pkey");

                    b.HasIndex("PostId");

                    b.ToTable("post_images", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameRole")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("name_role");

                    b.HasKey("Id")
                        .HasName("role_pkey");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameRole = "User"
                        },
                        new
                        {
                            Id = 2,
                            NameRole = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            NameRole = "Moderator"
                        });
                });

            modelBuilder.Entity("Cogni.Database.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tag");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdCategory")
                        .HasColumnType("integer")
                        .HasColumnName("id_category");

                    b.Property<string>("NameTag")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("name_tag");

                    b.HasKey("Id")
                        .HasName("tag_pkey");

                    b.HasIndex("IdCategory");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.TagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_category");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("tag_category_pkey");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tag_category", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AToken")
                        .HasColumnType("text");

                    b.Property<string>("BannerImage")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("email");

                    b.Property<int>("IdMbtiType")
                        .HasColumnType("integer")
                        .HasColumnName("id_mbti_type");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    b.Property<DateTime?>("LastLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("RToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("customuser_pkey");

                    b.HasIndex("IdMbtiType");

                    b.HasIndex("IdRole");

                    b.HasIndex(new[] { "Name" }, "customuser_name_key");

                    b.ToTable("customuser", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.UserTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user_tags");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTag")
                        .HasColumnType("integer")
                        .HasColumnName("id_tag");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.HasKey("Id")
                        .HasName("user_tags_pkey");

                    b.HasIndex("IdTag");

                    b.HasIndex("IdUser");

                    b.ToTable("user_tags", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.UserTagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user_tag_categories");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCategory")
                        .HasColumnType("integer")
                        .HasColumnName("id_category");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsBookmarked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_bookmarked");

                    b.HasKey("Id")
                        .HasName("user_tag_categories_pkey");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdUser", "IdCategory")
                        .IsUnique();

                    b.ToTable("user_tag_categories", (string)null);
                });

            modelBuilder.Entity("Cogni.Database.Entities.Article", b =>
                {
                    b.HasOne("Cogni.Database.Entities.User", "IdUserNavigation")
                        .WithMany("Articles")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("article_id_user_fkey");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Cogni.Database.Entities.ArticleImage", b =>
                {
                    b.HasOne("Cogni.Database.Entities.Article", "Article")
                        .WithMany("ArticleImages")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("article_images_article_id_fkey");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Avatar", b =>
                {
                    b.HasOne("Cogni.Database.Entities.User", "User")
                        .WithMany("Avatars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("avatars_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cogni.Database.Entities.ChatMember", b =>
                {
                    b.HasOne("Cogni.Database.Entities.Chat", "Chat")
                        .WithMany("Members")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Friend", b =>
                {
                    b.HasOne("Cogni.Database.Entities.User", "FriendNavigation")
                        .WithMany("FriendFriendNavigations")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("friends_friend_id_fkey");

                    b.HasOne("Cogni.Database.Entities.User", "User")
                        .WithMany("FriendUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("friends_user_id_fkey");

                    b.Navigation("FriendNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Like", b =>
                {
                    b.HasOne("Cogni.Database.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("likes_post_id_fkey");

                    b.HasOne("Cogni.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("likes_user_id_fkey");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Message", b =>
                {
                    b.HasOne("Cogni.Database.Entities.Avatar", null)
                        .WithMany("Messages")
                        .HasForeignKey("AvatarId");
                });

            modelBuilder.Entity("Cogni.Database.Entities.MessageStatus", b =>
                {
                    b.HasOne("Cogni.Database.Entities.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cogni.Database.Entities.Message", null)
                        .WithMany("MessageStatuses")
                        .HasForeignKey("MessageId");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Post", b =>
                {
                    b.HasOne("Cogni.Database.Entities.User", "IdUserNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("post_id_user_fkey");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Cogni.Database.Entities.PostImage", b =>
                {
                    b.HasOne("Cogni.Database.Entities.Post", "Post")
                        .WithMany("PostImages")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("post_images_post_id_fkey");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Tag", b =>
                {
                    b.HasOne("Cogni.Database.Entities.TagCategory", "IdCategoryNavigation")
                        .WithMany("Tags")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("tag_id_category_fkey");

                    b.Navigation("IdCategoryNavigation");
                });

            modelBuilder.Entity("Cogni.Database.Entities.User", b =>
                {
                    b.HasOne("Cogni.Database.Entities.MbtiType", "IdMbtiTypeNavigation")
                        .WithMany("Customusers")
                        .HasForeignKey("IdMbtiType")
                        .IsRequired()
                        .HasConstraintName("customuser_id_mbti_type_fkey");

                    b.HasOne("Cogni.Database.Entities.Role", "IdRoleNavigation")
                        .WithMany("Customusers")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("customuser_id_role_fkey");

                    b.Navigation("IdMbtiTypeNavigation");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("Cogni.Database.Entities.UserTag", b =>
                {
                    b.HasOne("Cogni.Database.Entities.Tag", "IdTagNavigation")
                        .WithMany("UserTags")
                        .HasForeignKey("IdTag")
                        .IsRequired()
                        .HasConstraintName("user_tags_id_tag_fkey");

                    b.HasOne("Cogni.Database.Entities.User", "IdUserNavigation")
                        .WithMany("UserTags")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("user_tags_id_user_fkey");

                    b.Navigation("IdTagNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Cogni.Database.Entities.UserTagCategory", b =>
                {
                    b.HasOne("Cogni.Database.Entities.TagCategory", "IdCategoryNavigation")
                        .WithMany("UserTagCategories")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_tag_categories_id_category_fkey");

                    b.HasOne("Cogni.Database.Entities.User", "IdUserNavigation")
                        .WithMany("UserTagCategories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_tag_categories_id_user_fkey");

                    b.Navigation("IdCategoryNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Article", b =>
                {
                    b.Navigation("ArticleImages");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Avatar", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Chat", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Cogni.Database.Entities.MbtiType", b =>
                {
                    b.Navigation("Customusers");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Message", b =>
                {
                    b.Navigation("MessageStatuses");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Post", b =>
                {
                    b.Navigation("PostImages");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Role", b =>
                {
                    b.Navigation("Customusers");
                });

            modelBuilder.Entity("Cogni.Database.Entities.Tag", b =>
                {
                    b.Navigation("UserTags");
                });

            modelBuilder.Entity("Cogni.Database.Entities.TagCategory", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("UserTagCategories");
                });

            modelBuilder.Entity("Cogni.Database.Entities.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Avatars");

                    b.Navigation("FriendFriendNavigations");

                    b.Navigation("FriendUsers");

                    b.Navigation("Posts");

                    b.Navigation("UserTagCategories");

                    b.Navigation("UserTags");
                });
#pragma warning restore 612, 618
        }
    }
}
